// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWB-IR4nLFgMRh3N1b7sr7b-9CAc3Y5z4',
    appId: '1:1008759966625:web:961c5ec23838e6992119e0',
    messagingSenderId: '1008759966625',
    projectId: 'uzaydan-misafirler-934a0',
    authDomain: 'uzaydan-misafirler-934a0.firebaseapp.com',
    storageBucket: 'uzaydan-misafirler-934a0.appspot.com',
    measurementId: 'G-DTY81EV3RT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_VAnu2sk9N0HS_iKqE3EgL-z8_Ij_2eA',
    appId: '1:1008759966625:android:ce7ffb5e6ed0bdfc2119e0',
    messagingSenderId: '1008759966625',
    projectId: 'uzaydan-misafirler-934a0',
    storageBucket: 'uzaydan-misafirler-934a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwx-apy_MqbTCBzqWv412HHmeljUx07uU',
    appId: '1:1008759966625:ios:7d18f6233c034d622119e0',
    messagingSenderId: '1008759966625',
    projectId: 'uzaydan-misafirler-934a0',
    storageBucket: 'uzaydan-misafirler-934a0.appspot.com',
    iosBundleId: 'com.example.uzaydanMisafirler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwx-apy_MqbTCBzqWv412HHmeljUx07uU',
    appId: '1:1008759966625:ios:7f70b24efab53f8f2119e0',
    messagingSenderId: '1008759966625',
    projectId: 'uzaydan-misafirler-934a0',
    storageBucket: 'uzaydan-misafirler-934a0.appspot.com',
    iosBundleId: 'com.example.uzaydanMisafirler.RunnerTests',
  );
}
